import type { Location } from './airtable';

/**
 * Mock locations for testing map functionality
 * Focused on Pacific Northwest region (Washington, Oregon, Northern California)
 */
export const mockLocations: Location[] = [
  // === LANDMARKS ===
  {
    id: 'loc-001',
    name: 'Mount Rainier Summit',
    latitude: 46.8523,
    longitude: -121.7603,
    description: 'The highest peak in the Cascade Range at 14,411 feet. Active stratovolcano with extensive glacial coverage.',
    category: 'Landmark',
    categories: ['Landmark', 'Mountain'],
    privacy: 'Public',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4',
    url: 'https://www.nps.gov/mora/index.htm',
  },
  {
    id: 'loc-002',
    name: 'Crater Lake',
    latitude: 42.9446,
    longitude: -122.1090,
    description: 'Deepest lake in the United States formed by collapsed volcano. Stunning blue water and Wizard Island.',
    category: 'Landmark',
    categories: ['Landmark', 'Lake'],
    privacy: 'Public',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4',
    url: 'https://www.nps.gov/crla/index.htm',
  },
  {
    id: 'loc-003',
    name: 'Multnomah Falls',
    latitude: 45.5762,
    longitude: -122.1158,
    description: 'Oregon\'s tallest waterfall at 620 feet. Iconic two-tier cascade with historic Benson Bridge.',
    category: 'Landmark',
    categories: ['Landmark', 'Waterfall'],
    privacy: 'Public',
    url: 'https://www.fs.usda.gov/recarea/crgnsa/recarea/?recid=29912',
  },
  {
    id: 'loc-004',
    name: 'Smith Rock State Park',
    latitude: 44.3672,
    longitude: -121.1407,
    description: 'World-renowned rock climbing destination. Towering rock formations along the Crooked River.',
    category: 'Landmark',
    categories: ['Landmark', 'Climbing'],
    privacy: 'Public',
    url: 'https://stateparks.oregon.gov/index.cfm?do=park.profile&parkId=36',
  },

  // === TRAILS ===
  {
    id: 'loc-005',
    name: 'Pacific Crest Trail: Bridge of the Gods',
    latitude: 45.6604,
    longitude: -121.9040,
    description: 'PCT crossing of Columbia River. Historic bridge connecting Washington and Oregon sections.',
    category: 'Trail',
    categories: ['Trail', 'Hiking'],
    privacy: 'Public',
    url: 'https://www.pcta.org/',
  },
  {
    id: 'loc-006',
    name: 'Enchantments: Aasgard Pass',
    latitude: 47.4757,
    longitude: -120.8037,
    description: 'Legendary alpine lakes region. Challenging permit-required hike with stunning scenery.',
    category: 'Trail',
    categories: ['Trail', 'Hiking', 'Alpine'],
    privacy: 'Public',
    url: 'https://www.fs.usda.gov/recarea/okawen/recarea/?recid=59441',
  },
  {
    id: 'loc-007',
    name: 'Eagle Creek Trail',
    latitude: 45.6387,
    longitude: -121.9194,
    description: 'Spectacular Columbia Gorge trail with waterfalls. Partially reopened after 2017 fire.',
    category: 'Trail',
    categories: ['Trail', 'Hiking', 'Waterfall'],
    privacy: 'Public',
  },
  {
    id: 'loc-008',
    name: 'Timberline Trail Loop',
    latitude: 45.3306,
    longitude: -121.7114,
    description: '40-mile circumnavigation of Mount Hood. Classic alpine loop with river crossings.',
    category: 'Trail',
    categories: ['Trail', 'Hiking', 'Mountain'],
    privacy: 'Public',
  },
  {
    id: 'loc-009',
    name: 'Spray Park Trail',
    latitude: 46.9247,
    longitude: -121.8419,
    description: 'Wildflower meadows below Mount Rainier. Peak bloom late July to early August.',
    category: 'Trail',
    categories: ['Trail', 'Hiking', 'Wildflowers'],
    privacy: 'Public',
  },
  {
    id: 'loc-010',
    name: 'Dog Mountain Trail',
    latitude: 45.6979,
    longitude: -121.7094,
    description: 'Steep Columbia Gorge trail famous for spring wildflowers. Challenging but rewarding views.',
    category: 'Trail',
    categories: ['Trail', 'Hiking', 'Wildflowers'],
    privacy: 'Public',
  },

  // === CAMPS ===
  {
    id: 'loc-011',
    name: 'Ohanapecosh Campground',
    latitude: 46.7334,
    longitude: -121.5667,
    description: 'Old-growth forest campground near Grove of the Patriarchs. Peaceful riverside setting.',
    category: 'Camp',
    categories: ['Camp', 'Camping'],
    privacy: 'Public',
    url: 'https://www.nps.gov/mora/planyourvisit/campgrounds.htm',
  },
  {
    id: 'loc-012',
    name: 'Colchuck Lake Camp',
    latitude: 47.5016,
    longitude: -120.8252,
    description: 'Alpine lake camping in the Enchantments. Permit required. Stunning mountain backdrop.',
    category: 'Camp',
    categories: ['Camp', 'Camping', 'Alpine'],
    privacy: 'Public',
  },
  {
    id: 'loc-013',
    name: 'Paradise Valley Dispersed',
    latitude: 45.3589,
    longitude: -121.7456,
    description: 'Backcountry camping along Timberline Trail. Multiple sites near Paradise Park meadows.',
    category: 'Camp',
    categories: ['Camp', 'Camping', 'Backcountry'],
    privacy: 'Public',
  },

  // === PRIVATE LOCATIONS (password protected) ===
  {
    id: 'loc-014',
    name: 'Secret Hot Springs',
    latitude: 44.3234,
    longitude: -121.8567,
    description: '[LOCKED] Remote natural hot springs. Please respect the area and leave no trace.',
    category: 'Hot Springs',
    categories: ['Hot Springs', 'Swimming'],
    privacy: 'Private',
    password: 'test123',
  },
  {
    id: 'loc-015',
    name: 'Hidden Climbing Crag',
    latitude: 45.7234,
    longitude: -121.5432,
    description: '[LOCKED] Newly developed sport climbing area. 5.8-5.12 routes on quality basalt.',
    category: 'Climbing',
    categories: ['Climbing', 'Sport'],
    privacy: 'Private',
    password: 'test123',
  },
  {
    id: 'loc-016',
    name: 'Private Wilderness Camp',
    latitude: 47.2345,
    longitude: -121.3456,
    description: '[LOCKED] Primitive camping on private land. Owner permission required.',
    category: 'Camp',
    categories: ['Camp', 'Camping', 'Private'],
    privacy: 'Private',
    password: 'test123',
  },

  // === CLIMBING AREAS ===
  {
    id: 'loc-017',
    name: 'Exit 38 Climbing Area',
    latitude: 47.4236,
    longitude: -121.4812,
    description: 'Year-round sport climbing near Seattle. Good for rainy days under overhangs.',
    category: 'Climbing',
    categories: ['Climbing', 'Sport'],
    privacy: 'Public',
    url: 'https://www.mountainproject.com/area/105794637/exit-38',
  },
  {
    id: 'loc-018',
    name: 'Tieton River Canyon',
    latitude: 46.6889,
    longitude: -120.9834,
    description: 'Excellent basalt sport climbing. Best in fall when reservoir is lowered.',
    category: 'Climbing',
    categories: ['Climbing', 'Sport'],
    privacy: 'Public',
  },

  // === LAKES & WATER ===
  {
    id: 'loc-019',
    name: 'Lake Chelan',
    latitude: 47.8416,
    longitude: -120.0218,
    description: 'One of deepest lakes in USA. Gateway to Stehekin and North Cascades backcountry.',
    category: 'Lake',
    categories: ['Lake', 'Boating'],
    privacy: 'Public',
  },
  {
    id: 'loc-020',
    name: 'Diablo Lake Overlook',
    latitude: 48.7200,
    longitude: -121.1282,
    description: 'Stunning turquoise glacial lake. Popular viewpoint along North Cascades Highway.',
    category: 'Lake',
    categories: ['Lake', 'Viewpoint'],
    privacy: 'Public',
  },
  {
    id: 'loc-021',
    name: 'Bagby Hot Springs',
    latitude: 44.9394,
    longitude: -122.1739,
    description: 'Rustic hot springs with hand-hewn log tubs. 1.5 mile hike from trailhead.',
    category: 'Hot Springs',
    categories: ['Hot Springs', 'Hiking'],
    privacy: 'Public',
    url: 'https://www.fs.usda.gov/recarea/mthood/recarea/?recid=53439',
  },

  // === VIEWPOINTS ===
  {
    id: 'loc-022',
    name: 'Artist Point',
    latitude: 48.8520,
    longitude: -121.6902,
    description: 'Iconic Mount Baker viewpoint. Accessible late summer when road opens.',
    category: 'Viewpoint',
    categories: ['Viewpoint', 'Mountain'],
    privacy: 'Public',
  },
  {
    id: 'loc-023',
    name: 'Rowena Crest',
    latitude: 45.6764,
    longitude: -121.3036,
    description: 'Columbia Gorge viewpoint with spring wildflowers. Historic Columbia River Highway.',
    category: 'Viewpoint',
    categories: ['Viewpoint', 'Wildflowers'],
    privacy: 'Public',
  },
  {
    id: 'loc-024',
    name: 'Hurricane Ridge',
    latitude: 47.9699,
    longitude: -123.4973,
    description: 'Olympic Peninsula viewpoint. Panoramic views of mountains and Strait of Juan de Fuca.',
    category: 'Viewpoint',
    categories: ['Viewpoint', 'Mountain'],
    privacy: 'Public',
    url: 'https://www.nps.gov/olym/planyourvisit/hurricane-ridge.htm',
  },

  // === SKI AREAS ===
  {
    id: 'loc-025',
    name: 'Crystal Mountain Resort',
    latitude: 46.9356,
    longitude: -121.4742,
    description: 'Largest ski area in Washington. Best Mount Rainier views from Summit House.',
    category: 'Ski Area',
    categories: ['Ski Area', 'Resort'],
    privacy: 'Public',
    url: 'https://www.crystalmountainresort.com/',
  },
  {
    id: 'loc-026',
    name: 'Mount Bachelor',
    latitude: 43.9792,
    longitude: -121.6889,
    description: 'Central Oregon ski resort. 360-degree summit skiing with Cascade views.',
    category: 'Ski Area',
    categories: ['Ski Area', 'Resort'],
    privacy: 'Public',
    url: 'https://www.mtbachelor.com/',
  },

  // === CITIES/TOWNS ===
  {
    id: 'loc-027',
    name: 'Leavenworth',
    latitude: 47.5962,
    longitude: -120.6615,
    description: 'Bavarian-themed town in Cascade Mountains. Gateway to Alpine Lakes Wilderness.',
    category: 'Town',
    categories: ['Town', 'Tourism'],
    privacy: 'Public',
  },
  {
    id: 'loc-028',
    name: 'Bend',
    latitude: 44.0582,
    longitude: -121.3153,
    description: 'Outdoor recreation hub of Central Oregon. Skiing, climbing, mountain biking, breweries.',
    category: 'Town',
    categories: ['Town', 'Tourism'],
    privacy: 'Public',
  },
  {
    id: 'loc-029',
    name: 'Hood River',
    latitude: 45.7054,
    longitude: -121.5212,
    description: 'Windsurfing and kiteboarding capital. Gorge gateway with craft breweries.',
    category: 'Town',
    categories: ['Town', 'Tourism', 'Windsurfing'],
    privacy: 'Public',
  },

  // === ADDITIONAL ALPINE LOCATIONS FOR CLUSTERING TEST ===
  {
    id: 'loc-030',
    name: 'Goat Rocks Wilderness',
    latitude: 46.5134,
    longitude: -121.4523,
    description: 'Rugged PCT section with knife-edge ridge. Excellent late summer backpacking.',
    category: 'Wilderness',
    categories: ['Wilderness', 'Hiking', 'Backpacking'],
    privacy: 'Public',
  },
  {
    id: 'loc-031',
    name: 'Alpine Lakes Wilderness HQ',
    latitude: 47.5500,
    longitude: -121.1500,
    description: 'Over 700 alpine lakes. Popular wilderness area east of Seattle.',
    category: 'Wilderness',
    categories: ['Wilderness', 'Hiking', 'Alpine'],
    privacy: 'Public',
  },
  {
    id: 'loc-032',
    name: 'Three Sisters Wilderness',
    latitude: 44.1500,
    longitude: -121.7667,
    description: 'Volcanic peaks and lava flows. Extensive trail network in Central Oregon.',
    category: 'Wilderness',
    categories: ['Wilderness', 'Hiking', 'Volcanic'],
    privacy: 'Public',
  },

  // === COASTAL LOCATIONS ===
  {
    id: 'loc-033',
    name: 'Cannon Beach',
    latitude: 45.8918,
    longitude: -123.9615,
    description: 'Iconic Oregon coast with Haystack Rock. Tide pools and sea stacks.',
    category: 'Beach',
    categories: ['Beach', 'Coast'],
    privacy: 'Public',
  },
  {
    id: 'loc-034',
    name: 'Ruby Beach',
    latitude: 47.7097,
    longitude: -124.4145,
    description: 'Olympic Coast beach with sea stacks. Popular photography location.',
    category: 'Beach',
    categories: ['Beach', 'Coast'],
    privacy: 'Public',
  },
  {
    id: 'loc-035',
    name: 'Cape Flattery',
    latitude: 48.3831,
    longitude: -124.7141,
    description: 'Northwesternmost point in contiguous US. Dramatic cliffs and sea caves.',
    category: 'Viewpoint',
    categories: ['Viewpoint', 'Coast'],
    privacy: 'Public',
  },

  // === ADDITIONAL TESTING LOCATIONS (clustered near Seattle for zoom testing) ===
  {
    id: 'loc-036',
    name: 'Rattlesnake Ledge',
    latitude: 47.4354,
    longitude: -121.7709,
    description: 'Popular Seattle-area hike. Great views for minimal effort.',
    category: 'Trail',
    categories: ['Trail', 'Hiking'],
    privacy: 'Public',
  },
  {
    id: 'loc-037',
    name: 'Little Si',
    latitude: 47.4881,
    longitude: -121.7531,
    description: 'Shorter alternative to Mount Si. Excellent viewpoint at summit.',
    category: 'Trail',
    categories: ['Trail', 'Hiking'],
    privacy: 'Public',
  },
  {
    id: 'loc-038',
    name: 'Mount Si',
    latitude: 47.4881,
    longitude: -121.7231,
    description: 'Classic Seattle hike. 3,150 feet of elevation gain in 4 miles.',
    category: 'Trail',
    categories: ['Trail', 'Hiking'],
    privacy: 'Public',
  },
  {
    id: 'loc-039',
    name: 'Mailbox Peak',
    latitude: 47.4675,
    longitude: -121.6794,
    description: 'Steep and challenging hike. Actual mailbox at summit for trail register.',
    category: 'Trail',
    categories: ['Trail', 'Hiking'],
    privacy: 'Public',
  },
  {
    id: 'loc-040',
    name: 'Granite Mountain Lookout',
    latitude: 47.4003,
    longitude: -121.4519,
    description: 'Historic fire lookout with 360-degree Cascade views.',
    category: 'Trail',
    categories: ['Trail', 'Hiking', 'Lookout'],
    privacy: 'Public',
  },
];

/**
 * Mock location for initial map center (approximately Cascade Range)
 */
export const DEFAULT_CENTER: [number, number] = [46.2, -121.8];
export const DEFAULT_ZOOM = 7;
