// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/projects": {
    params: {};
  };
  "/projects/:slug": {
    params: {
      "slug": string;
    };
  };
  "/about": {
    params: {};
  };
  "/contact": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/projects" | "/projects/:slug" | "/about" | "/contact";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/projects.tsx": {
    id: "routes/projects";
    page: "/projects";
  };
  "routes/projects.$slug.tsx": {
    id: "routes/projects.$slug";
    page: "/projects/:slug";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/projects": typeof import("./app/routes/projects.tsx");
  "routes/projects.$slug": typeof import("./app/routes/projects.$slug.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
  "routes/contact": typeof import("./app/routes/contact.tsx");
};