name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2

      - name: Test Output
        ## Reference your environment variables
        run: echo "Posts Table Name:${{ secrets.AIRTABLE_POSTS_TABLENAME }}"

      - name: Build the Docker image
        env:
          GATSBY_ALGOLIA_APP_ID: ${{ secrets.GATSBY_ALGOLIA_APP_ID }}
          GATSBY_ALGOLIA_INDEX_NAME: ${{ secrets.GATSBY_ALGOLIA_INDEX_NAME }}
          GATSBY_ALGOLIA_SEARCH_KEY: ${{ secrets.GATSBY_ALGOLIA_SEARCH_KEY }}
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_POSTS_BASEID: ${{ secrets.AIRTABLE_POSTS_BASEID }}
          AIRTABLE_POSTS_TABLENAME: ${{ secrets.AIRTABLE_POSTS_TABLENAME }}
          AIRTABLE_QUALIFICATIONS_TABLENAME: ${{ secrets.AIRTABLE_QUALIFICATIONS_TABLENAME }}
          AIRTABLE_WEBSITES_TABLENAME: ${{ secrets.AIRTABLE_WEBSITES_TABLENAME }}
        run: docker build . --file Dockerfile --tag loidolt-design:$(date +%s)
